spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:csv_playground}
    username: ${DB_USER:appuser}
    password: ${DB_PASSWORD:apppassword}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

logging:
  level:
    root: INFO
    com.csvplayground: DEBUG 