version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: csv_playground_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: csv_playground
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: ./mark1
      dockerfile: Dockerfile
    container_name: csv_playground_go
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=csv_playground
    depends_on:
      mysql:
        condition: service_healthy

  spring-app:
    build:
      context: ./mark2
      dockerfile: Dockerfile
    container_name: csv_playground_spring
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/csv_playground
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppassword
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 